# EventHub API Test Configuration
base.url=https://eventhub.rahulshettyacademy.com
api.url=https://api.eventhub.rahulshettyacademy.com/api
user.email=mafdangowda8095@gmail.com
user.password=Madan@123
